### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by marcelosomers**
- [x] Remove unneeded files in `init` that are automatically generated by PatternPack v1.0.2+
- [ ] `pattern` filenames are always `pattern.md` and `pattern.scss`

### CODE REVIEW

**Comment by marcelosomers** [comment]
@johngully The Yeoman generator for patterns always seems to generate `<location>/<pattern name>/pattern.md` and `<location>/<pattern name>/pattern.scss`

Was it intentional to nest them within a folder? Everywhere else we've used the pattern of `<location>/<pattern name>.md or .scss`

**Comment by johngully** [comment]
We should be creating patterns using the "type of pattern" and "pattern name".  

```
{src}/{pattern-type}/{pattern-name}.md
{src}/{pattern-type}/{pattern-name}.{css-type}
```

Example

```
./src/atoms/buttons.md
./src/atoms/buttons.scss
```

**Comment by johngully** [comment]
I think we should take a look at keeping some of the empty folders.  

What happens if the `/dist` folder is configured but does not exists?  If it is created, then we should not make it part of the generator, if it breaks then we should do something about that.

I think giving the user a place to put `images` and `js` has some value, because it provides direction.  I know they can do whatever they like, but the idea of the generator is to provide an opinion of what to do.

**Comment by marcelosomers** [comment]
> We should be creating patterns using the "type of pattern" and "pattern name".

Do you remember how to do this from the Yeoman docs? I can go dig if you can't.

> We may want to consider creating this file. It allows the user to immediately modify the file before running a build. But if we keep this file, it should use the same template as the one in the patternpack project

The thinking here was to keep Yeoman as "stripped down" as possible for future debugging. Basically offload as much file generation to PatternPack as we are willing to build in, and use Yeoman to extend that.

> What happens if the /dist folder is configured but does not exists? If it is created, then we should not make it part of the generator, if it breaks then we should do something about that.

I'll double check, but I don't think anything breaks. `/dist` is not generated by default with PatternPack, but it gets created upon `patternpack:release`.

> I think giving the user a place to put images and js has some value, because it provides direction. I know they can do whatever they like, but the idea of the generator is to provide an opinion of what to do.

I can see your point. I'll add those but leave the generation of everything else up to PatternPack.

**Comment by johngully** [comment]
The generator has been published at v0.9.0

**Pull request closed without merging**
